[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_port = COM3
upload_port = COM3
build_flags =
    -DUSER_SETUP_LOADED
    -DGC9A01_DRIVER
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=21
    -DTFT_RST=22
    -DTFT_MISO=-1
    -DSPI_FREQUENCY=10000000
    -DLOAD_GLCD
    -DLOAD_FONT2
    -DLOAD_FONT4
    -DLOAD_FONT6
    -DLOAD_FONT7
    -DLOAD_FONT8
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    densaugeo/base64 @ ^1.4.0
    bodmer/TFT_eSPI @ ^2.5.43